[tool.black]
line-length = 88
target-version = ["py310"]
exclude = "migrations|venv|env|\\.venv|__pycache__|node_modules"

[tool.isort]
profile = "black"
line_length = 88
skip = ["migrations", "venv", "env", ".venv", "__pycache__", "node_modules"]

[tool.flake8]
max-line-length = 88
exclude = "migrations,venv,env,.venv,__pycache__,node_modules"
